name = "wolfpack-utm-pixel"
type = "web_pixel_extension"
uid = "9c39afc7-f730-af5d-e507-823597e5186693eb73cf"

runtime_context = "strict"

[customer_privacy]
analytics = true
marketing = true
preferences = false
sale_of_data = "disabled"

[settings]
type = "object"

[settings.fields.app_server_url]
name = "App Server URL"
description = "The URL of the Wolfpack app server for attribution tracking"
type = "single_line_text_field"
validations = [
  { name = "min", value = "1" }
]
