# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bfda5624970c7ada838998eb951e9e85"
name = "bundle-discount-functions"
handle = "bundle-discount-functions-1"
application_url = "https://internship-transaction-expert-argument.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,write_discounts,write_products,read_themes,write_themes"

[auth]
redirect_urls = ["https://internship-transaction-expert-argument.trycloudflare.com/auth/callback", "https://internship-transaction-expert-argument.trycloudflare.com/auth/shopify/callback", "https://internship-transaction-expert-argument.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
