# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a383172f42c2ab283901a663d485a03d"
name = "Wolfpack: Product Bundles"
handle = "wolfpack-product-bundles-4"
application_url = "https://davis-administrators-deeper-viewpicture.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://davis-administrators-deeper-viewpicture.trycloudflare.com/auth/callback",
  "https://davis-administrators-deeper-viewpicture.trycloudflare.com/auth/shopify/callback",
  "https://davis-administrators-deeper-viewpicture.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
