# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bfda5624970c7ada838998eb951e9e85"
name = "bundle-discount-functions"
handle = "bundle-discount-functions-1"
application_url = "https://palestinian-optional-translation-mills.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts, write_products, read_content"

[auth]
redirect_urls = [
  "https://palestinian-optional-translation-mills.trycloudflare.com/auth/callback",
  "https://palestinian-optional-translation-mills.trycloudflare.com/auth/shopify/callback",
  "https://palestinian-optional-translation-mills.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
