# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "63077bb0483a6ce08a2d6139b14d170b"
name = "Wolfpack: Product Bundles -SIT"
application_url = "https://wolfpack-product-bundle-app-sit.onrender.com"
embedded = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [
  "products/update",
  "products/delete",
  "app_subscriptions/update",
  "app_purchases_one_time/update",
  "app/uninstalled",
  "app/scopes_update"
]
  uri = "pubsub://light-quest-455608-i3:wolfpack-product-bundles-staging"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_product_listings,read_products,read_publications,read_themes,unauthenticated_read_content,unauthenticated_read_product_listings,write_app_proxy,write_cart_transforms,write_content,write_discounts,write_products,write_publications,write_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://wolfpack-product-bundle-app-sit.onrender.com/auth/callback",
  "https://wolfpack-product-bundle-app-sit.onrender.com/auth/shopify/callback",
  "https://wolfpack-product-bundle-app-sit.onrender.com/api/auth/callback"
]

[app_proxy]
url = "https://wolfpack-product-bundle-app-sit.onrender.com"
subpath = "product-bundles"
prefix = "apps"

[metafields]
api_version = "2025-10"

[shop.metafields.app.serverUrl]
type = "single_line_text_field"
name = "App Server URL"
description = "URL of the app server for widget API calls"

  [shop.metafields.app.serverUrl.access]
  admin = "merchant_read_write"
  storefront = "public_read"
