/// Domain types for bundle cart transform.
///
/// These are JSON-deserialized from Shopify metafield values — NOT generated
/// by #[typegen]. typegen handles the cart input + operation output schema;
/// these types handle the business-logic JSON payloads stored in metafields.
///
/// OUTPUT structs (FunctionRunResult, CartOperation, MergeOperation, etc.)
/// come from crate::schema (generated by #[typegen]) and implement
/// shopify_function_wasm_api::Serialize. Do NOT redefine them here.

// ============================================================================
// METAFIELD JSON TYPES — deserialized from metafield string values
// ============================================================================

/// Deserialized from `$app:component_parents` metafield (JSON array).
/// One entry per bundle parent; we always use index [0].
/// Only `id` and `price_adjustment` are needed by the MERGE path.
/// (`component_reference`/`component_quantities` live on separate metafields
/// and are read directly via typegen accessors in the EXPAND path.)
#[derive(serde::Deserialize, Debug)]
pub struct ComponentParent {
    /// Parent variant GID, e.g. "gid://shopify/ProductVariant/123"
    pub id: String,
    #[serde(default)]
    pub price_adjustment: Option<PriceAdjustmentConfig>,
}

/// Deserialized from `$app:price_adjustment` metafield.
/// Also embedded inside `ComponentParent.price_adjustment`.
#[derive(serde::Deserialize, Debug, Clone, Default)]
pub struct PriceAdjustmentConfig {
    #[serde(default)]
    pub method: PricingMethod,
    #[serde(default)]
    pub value: f64,
    #[serde(default)]
    pub conditions: Option<Condition>,
}

#[derive(serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "snake_case")]
pub enum PricingMethod {
    #[default]
    PercentageOff,
    FixedAmountOff,
    FixedBundlePrice,
}

/// Optional discount threshold condition.
#[derive(serde::Deserialize, Debug, Clone)]
pub struct Condition {
    #[serde(rename = "type")]
    pub condition_type: ConditionType,
    pub operator: String,
    pub value: f64,
}

#[derive(serde::Deserialize, Debug, Clone, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum ConditionType {
    Quantity,
    Amount,
}

/// Normalized condition operator.
#[derive(Debug, Clone, PartialEq)]
pub enum Operator {
    Gte,
    Gt,
    Lte,
    Lt,
    Eq,
}

/// Deserialized from `$app:component_pricing` metafield (JSON array).
#[derive(serde::Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct ComponentPricingItem {
    pub variant_id: String,
    #[serde(default)]
    pub title: Option<String>,
    pub retail_price: i64,
    pub bundle_price: i64,
    pub discount_percent: f64,
    pub savings_amount: i64,
}
