/// Domain types for bundle cart transform.
///
/// These are JSON-deserialized from Shopify metafield values — NOT generated
/// by #[typegen]. typegen handles the cart input + operation output schema;
/// these types handle the business-logic JSON payloads stored in metafields.
///
/// OUTPUT structs (FunctionRunResult, CartOperation, MergeOperation, etc.)
/// come from crate::schema (generated by #[typegen]) and implement
/// shopify_function_wasm_api::Serialize. Do NOT redefine them here.

// ============================================================================
// METAFIELD JSON TYPES — deserialized from metafield string values
// ============================================================================

/// Deserialized from `$app:component_parents` metafield (JSON array).
/// One entry per bundle parent. The MERGE path chooses the entry whose
/// component references best match the grouped cart lines.
/// (`component_reference`/`component_quantities` live on separate metafields
/// and are read directly via typegen accessors in the EXPAND path.)
#[derive(serde::Deserialize, Debug)]
pub struct ComponentParent {
    /// Parent variant GID, e.g. "gid://shopify/ProductVariant/123"
    pub id: String,
    #[serde(default)]
    pub component_reference: Option<MetafieldValue<Vec<String>>>,
    #[serde(default)]
    pub price_adjustment: Option<PriceAdjustmentConfig>,
}

#[derive(serde::Deserialize, Debug, Clone)]
pub struct MetafieldValue<T> {
    #[serde(default)]
    pub value: T,
}

/// Deserialized from `$app:price_adjustment` metafield.
/// Also embedded inside `ComponentParent.price_adjustment`.
#[derive(serde::Deserialize, Debug, Clone, Default)]
#[serde(rename_all = "camelCase")]
pub struct PriceAdjustmentConfig {
    #[serde(default)]
    pub method: PricingMethod,
    #[serde(default)]
    pub value: f64,
    #[serde(default)]
    pub conditions: Option<Condition>,
    #[serde(default)]
    pub customer_buys: Option<i64>,
    #[serde(default)]
    pub customer_gets: Option<i64>,
    #[serde(default)]
    pub discount_type: Option<String>,
    #[serde(default)]
    pub apply_discount_to: Option<String>,
}

#[derive(serde::Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "snake_case")]
pub enum PricingMethod {
    #[default]
    PercentageOff,
    FixedAmountOff,
    FixedBundlePrice,
    BuyXGetY,
}

/// Optional discount threshold condition.
#[derive(serde::Deserialize, Debug, Clone)]
pub struct Condition {
    #[serde(rename = "type")]
    pub condition_type: ConditionType,
    pub operator: String,
    pub value: f64,
}

#[derive(serde::Deserialize, Debug, Clone, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum ConditionType {
    Quantity,
    Amount,
}

/// Normalized condition operator.
#[derive(Debug, Clone, PartialEq)]
pub enum Operator {
    Gte,
    Gt,
    Lte,
    Lt,
    Eq,
}

/// Deserialized from `$app:component_pricing` metafield (JSON array).
#[derive(serde::Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct ComponentPricingItem {
    pub variant_id: String,
    #[serde(default)]
    pub title: Option<String>,
    #[serde(default)]
    pub image_url: Option<String>,
    pub retail_price: i64,
    pub bundle_price: i64,
    pub discount_percent: f64,
    pub savings_amount: i64,
}

#[derive(serde::Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct CartLineMessagingSettings {
    #[serde(default = "default_true")]
    pub is_enabled: bool,
    #[serde(default = "default_true")]
    pub show_bundle_contains: bool,
    #[serde(default = "default_true")]
    pub show_original_price: bool,
    #[serde(default)]
    pub discount_display: CartLineDiscountDisplaySettings,
}

impl Default for CartLineMessagingSettings {
    fn default() -> Self {
        Self {
            is_enabled: true,
            show_bundle_contains: true,
            show_original_price: true,
            discount_display: CartLineDiscountDisplaySettings::default(),
        }
    }
}

#[derive(serde::Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct CartLineDiscountDisplaySettings {
    #[serde(default = "default_true")]
    pub is_enabled: bool,
    #[serde(default = "default_amount_percentage")]
    pub format: String,
}

impl Default for CartLineDiscountDisplaySettings {
    fn default() -> Self {
        Self {
            is_enabled: true,
            format: default_amount_percentage(),
        }
    }
}

fn default_true() -> bool {
    true
}

fn default_amount_percentage() -> String {
    "amount_percentage".to_string()
}

#[derive(serde::Deserialize, Debug, Clone, Default)]
#[serde(rename_all = "camelCase")]
pub struct CartLineDisplayProperties {
    #[serde(default, rename = "box")]
    pub box_label: Option<String>,
    #[serde(default)]
    pub items: Option<String>,
    #[serde(default)]
    pub retail_price: Option<String>,
    #[serde(default)]
    pub you_save: CartLineDisplaySavings,
}

#[derive(serde::Deserialize, Debug, Clone, Default)]
#[serde(rename_all = "camelCase")]
pub struct CartLineDisplaySavings {
    #[serde(default)]
    pub amount: Option<String>,
    #[serde(default)]
    pub percentage: Option<String>,
    #[serde(default)]
    pub amount_percentage: Option<String>,
}
