name = "bundle-builder"

[build]
asset_dir = "assets"

[[extensions]]
name = "bundle-builder"
type = "theme"
handle = "bundle-builder"
api_version = "2025-04" # Or the latest stable API version you intend to use.

[[extensions.blocks]]
target = "all"
liquid_path = "blocks/bundle.liquid"

