name = "bundle-builder"

[build]
asset_dir = "assets"

[[extensions]]
name = "bundle-builder"

uid = "23b807f7-472d-4f93-e241-5a1e079d6b51548daaf2"

type = "theme"
handle = "bundle-builder"
api_version = "2025-04" # Or the latest stable API version you intend to use.

[[extensions.blocks]]
target = "section-group:product-form"
liquid_path = "blocks/bundle-product-page.liquid"

[[extensions.blocks]]
target = "section:main-product"
liquid_path = "blocks/bundle-product-page.liquid"

[[extensions.blocks]]
target = "all"
liquid_path = "blocks/bundle-product-page.liquid"

# Full-Page Bundle Block (for standalone pages)
[[extensions.blocks]]
target = "section"
liquid_path = "blocks/bundle-full-page.liquid"

