-- AlterTable
ALTER TABLE "public"."DesignSettings" ADD COLUMN     "modalBgColor" TEXT DEFAULT '#FFFFFF',
ADD COLUMN     "modalBorderRadius" INTEGER DEFAULT 12,
ADD COLUMN     "modalButtonBgColor" TEXT DEFAULT '#000000',
ADD COLUMN     "modalButtonBorderRadius" INTEGER DEFAULT 8,
ADD COLUMN     "modalButtonTextColor" TEXT DEFAULT '#FFFFFF',
ADD COLUMN     "modalPriceFontSize" INTEGER DEFAULT 22,
ADD COLUMN     "modalTitleFontSize" INTEGER DEFAULT 28,
ADD COLUMN     "modalTitleFontWeight" INTEGER DEFAULT 700,
ADD COLUMN     "modalVariantBorderRadius" INTEGER DEFAULT 8,
ADD COLUMN     "productCardBorderColor" TEXT DEFAULT 'rgba(0,0,0,0.08)',
ADD COLUMN     "productCardBorderRadius" INTEGER DEFAULT 8,
ADD COLUMN     "productCardBorderWidth" INTEGER DEFAULT 1,
ADD COLUMN     "productCardHeight" INTEGER DEFAULT 420,
ADD COLUMN     "productCardHoverShadow" TEXT DEFAULT '0 8px 24px rgba(0,0,0,0.12)',
ADD COLUMN     "productCardPadding" INTEGER DEFAULT 12,
ADD COLUMN     "productCardShadow" TEXT DEFAULT '0 2px 8px rgba(0,0,0,0.04)',
ADD COLUMN     "productCardSpacing" INTEGER DEFAULT 20,
ADD COLUMN     "productCardWidth" INTEGER DEFAULT 280,
ADD COLUMN     "productImageBgColor" TEXT DEFAULT '#F8F8F8',
ADD COLUMN     "productImageBorderRadius" INTEGER DEFAULT 6,
ADD COLUMN     "productImageHeight" INTEGER DEFAULT 280;
