api_version = "2025-10"

[[extensions]]
name = "Bundle Cart Transform"
handle = "bundle-cart-transform-ts"

uid = "06d00551-8da0-9b28-79e8-63af90adb1019dc2f112"

type = "function"

description = "Transform cart lines to display bundles as single items with discount pricing"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart-transform-input.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"